# Generated by Django 5.2.17 on 2026-09-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='عباس داورپناه', max_length=80, verbose_name='نام')),
                ('kicker', models.CharField(default='ترویج فلسفه نرم\u200cافزار آزاد', max_length=120, verbose_name='خط بالا')),
                ('intro', models.TextField(default='برگزارکننده و نویسنده. از شیرازلاگ و فینگرکدر تا گفتگو با کسانی که آزادی کاربر را جدی می\u200cگیرند — متن\u200cها از دل کار جمعی می\u200cآیند، نه از روی کاتالوگ ابزار.', verbose_name='معرفی')),
                ('mastodon', models.URLField(blank=True, default='https://techhub.social/@abbas_dp')),
                ('pixelfed', models.URLField(blank=True, default='https://pixelfed.social/davarpanah')),
                ('codeberg', models.URLField(blank=True, default='https://codeberg.org/abbasdp')),
                ('matrix', models.URLField(blank=True, default='https://matrix.to/#/@abbas_dp:matrix.org')),
                ('gnu_url', models.URLField(blank=True, default='https://www.gnu.org/philosophy/free-sw.fa.html')),
                ('shirazlinux', models.URLField(blank=True, default='https://sudoshz.ir')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='نامک')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='نامک')),
                ('excerpt', models.TextField(blank=True, verbose_name='خلاصه')),
                ('body', models.TextField(verbose_name='متن HTML')),
                ('cover', models.ImageField(blank=True, upload_to='covers/', verbose_name='تصویر شاخص')),
                ('cover_alt', models.CharField(blank=True, max_length=250, verbose_name='متن جایگزین تصویر')),
                ('cover_caption', models.CharField(blank=True, max_length=250, verbose_name='شرح تصویر')),
                ('published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('featured', models.BooleanField(default=False, verbose_name='برگزیده')),
                ('published_at', models.DateTimeField(verbose_name='تاریخ انتشار')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('tags', models.ManyToManyField(blank=True, to='journal.tag', verbose_name='برچسب\u200cها')),
            ],
            options={
                'verbose_name': 'نوشته',
                'verbose_name_plural': 'نوشته\u200cها',
                'ordering': ['-published_at'],
            },
        ),
    ]
